version: '3'
services:

  django:
    image: melodi-presto/django
    restart: always
    container_name: melodi-presto-django
    build:
      context: .
    networks:
      - dsne-django-nginx
    volumes:
      - ${PROJECT_DIR}/static:/usr/src/app/static
      - ${PROJECT_DIR}/django_project:/usr/src/app/django_project
    ports:
      - 8801:8000

  nginx:
    image: melodi-presto/nginx
    restart: always
    container_name: melodi-presto-nginx
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    networks:
      - dsne-django-nginx
    volumes:
      - ${PROJECT_DIR}/static:/usr/src/app/static
    ports:
      - 9091:80
    depends_on:
      - django

  elastic:
    image: elasticsearch:7.17.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${PROJECT_DIR}/elastic:/usr/share/elasticsearch/data
    networks:
      - dsne-django-nginx
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: false
      search.max_buckets: 100000
    ports:
      - 9200:9200

volumes:
  dsne-django-static:
  django_project:

networks:
  dsne-django-nginx:
    driver: bridge
