name: MelodiPresto

channels:
  - akode
  - conda-forge

dependencies:
  - python=3.8
  - black
  - scipy
  - gunicorn
  - djangorestframework
  - requests
  - elasticsearch
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - pydot
  - loguru
  - pip
  - pip:
    - drf-yasg
    - Django>=2.2.18
    - coreapi

